version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: master
    commit-message:
      prefix: "fix"
    allow:
      - dependency-type: production
      - dependency-name: "rxjs"
        dependency-type: "development"
    ignore:
      - dependency-name: "tslib"
