version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: master
    commit-message:
      prefix: "build"
    allow:
      - dependency-type: production
    ignore:
      - dependency-name: "tslib"

  # Still need to copy the above for the beta branch
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: beta
    commit-message:
      prefix: "build"
    allow:
      - dependency-type: production
    ignore:
      - dependency-name: "tslib"
