name: CI

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

jobs:
  testRelease:
    name: Test - Release
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: write
    env:
      CI: true
      BRANCH: ${{ github.ref_name }}
      PR_OPENED_BY: ${{ github.event.pull_request.user.login }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      # https://github.com/wagoid/commitlint-github-action/issues/617 & https://github.com/wagoid/commitlint-github-action/issues/560
      - name: Temporary fix for wagoid/commitlint-github-action@v5.3.0
        run: mv tsconfig.json __tsconfig.json__

      - name: Lint commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v5.3.0

      # Revert fix
      - name: Revert temporary fix for wagoid/commitlint-github-action@v5.3.0
        run: mv __tsconfig.json__ tsconfig.json

      - name: Install
        if: ${{ env.PR_OPENED_BY != 'dependabot[bot]' }}
        run: npm ci

      - name: Install (Dependabot)
        if: ${{ env.PR_OPENED_BY == 'dependabot[bot]' }}
        run: npm ci || npm i

      - name: Test
        if: ${{ env.PR_OPENED_BY != 'dependabot[bot]' }}
        run: npm run test

      - name: Test (Dependabot)
        if: ${{ env.PR_OPENED_BY == 'dependabot[bot]' }}
        run: npm run test:full

      - name: Configure git user
        if: ${{ github.event_name == 'push' }} || ${{ env.PR_OPENED_BY == 'dependabot[bot]' }}
        run: |
          git config --global user.email "ci@ci.com"
          git config --global user.name "ci"

      - name: Commit changes (Dependabot)
        if: ${{ env.PR_OPENED_BY == 'dependabot[bot]' }}
        run: |
          git add -A
          git diff-index --quiet HEAD || commit -m "build: changes from dependabot install [skip ci]"
          git push

      - name: Version
        if: ${{ github.event_name == 'push' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run version -- branch=$BRANCH

      - name: Npm release
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release -- branch=$BRANCH
