name: Dependency update on branch

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch:
        description: master, beta
        required: true
        type: string

jobs:
  checkDependencies:
    name: Updated dependencies
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: Update package.json's
        run: npm run deps:update:latest:ci

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: [automated update] updated dependencies"
          branch: ${{ inputs.branch }}_auto_dependency_update
          delete-branch: true
          title: "[Auto dependency update] - ${{ inputs.branch }}"
          body: |
            - Automatic dependency update for ${{ inputs.branch }}
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            automated update
            dependencies
