name: Test

on:
  push:
    branches: [master, beta, next]
  pull_request:
    branches: [master, beta, next]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Lint commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v4

      - name: Install
        run: npm run bootstrap:ci

      - name: Test
        run: npm run test
